services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "5001:5000"
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    command: nodemon --legacy-watch index.js
    restart: always
    environment:
      - HOST=db
      - USER=postgres
      - PASSWORD=postgres
      - DB=app_db
      - DBPORT=5432           # ✅ ใช้ 5432 ไม่ใช่ 5433 ด้านใน container
      - PORT=5000             # ✅ SERVER_POST --> PORT
      - DIALECT=postgres
    depends_on:
      - db

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server

  db:
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"   # ✅ ด้านนอกใช้ 5433, ด้านในใช้ 5432 (มาตรฐาน Postgres)
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
